const perguntaModel = require('../models/perguntaModel');
const alternativaModel = require('../models/alternativaModel');
const usuarioModel = require('../models/usuarioModel');
const quizModel = require('../models/quizModel');
async function iniciar(categoriaId = null) { const perguntas = await perguntaModel.listarAtivasPorCategoria(categoriaId); const resultado = []; for (const pergunta of perguntas) { const alternativas = await alternativaModel.listarPorPergunta(pergunta.id); resultado.push({ ...pergunta, alternativas: alternativas.map((alt) => ({ id: alt.id, pergunta_id: alt.pergunta_id, texto: alt.texto })) }); } return resultado; }
async function finalizar({ usuario, respostas }) { if (!usuario || !usuario.nome) { const error = new Error('O nome do usuário é obrigatório.'); error.status = 400; throw error; } if (!Array.isArray(respostas) || respostas.length === 0) { const error = new Error('A lista de respostas é obrigatória.'); error.status = 400; throw error; } const usuarioCriado = await usuarioModel.criarOuBuscar(usuario); let totalAcertos = 0; const respostasCalculadas = []; for (const resposta of respostas) { const alternativa = await quizModel.buscarAlternativa(resposta.alternativa_id); if (!alternativa) { const error = new Error(`Alternativa ${resposta.alternativa_id} não encontrada.`); error.status = 400; throw error; } const correta = alternativa.correta === 1; if (correta) totalAcertos += 1; respostasCalculadas.push({ pergunta_id: resposta.pergunta_id, alternativa_id: resposta.alternativa_id, correta }); } const totalPerguntas = respostas.length; const totalErros = totalPerguntas - totalAcertos; const pontuacao = totalAcertos * 10; const tentativa = await quizModel.criarTentativa({ usuario_id: usuarioCriado.id, pontuacao, total_perguntas: totalPerguntas, total_acertos: totalAcertos, total_erros: totalErros }); for (const resposta of respostasCalculadas) await quizModel.registrarResposta({ tentativa_id: tentativa.id, pergunta_id: resposta.pergunta_id, alternativa_id: resposta.alternativa_id, correta: resposta.correta }); const respostasDetalhadas = await quizModel.respostasDaTentativa(tentativa.id); return { tentativa, usuario: usuarioCriado, respostas: respostasDetalhadas }; }
async function listarTentativas() { return quizModel.listarTentativas(); }
async function resultado(id) { const tentativa = await quizModel.buscarTentativa(id); if (!tentativa) { const error = new Error('Tentativa não encontrada.'); error.status = 404; throw error; } const respostas = await quizModel.respostasDaTentativa(id); return { tentativa, respostas }; }
module.exports = { iniciar, finalizar, listarTentativas, resultado };
